### ISSUE TITLE
Explain usage in docs

### ISSUE THREAD

**Issue by alirezaalavi87** [dobidi/logseq-bidi#20]
Hi, 
Thank you for the great plugin,
I installed it yesterday and it took me until today to understand how it works from a user's perspective. meaning, I was looking for some icon or key shortcut to toggle RTL/LTR/Auto mode, like you can in [obsidian rtl](https://github.com/esm7/obsidian-rtl).

I highly suggest explaining that this extension works passively, and not actively, meaning the user shouldn't do anything as it causes confusion.

**Comment by ahangarha** [comment]
Hi

Happy to hear you liked the plugin.

Well, you don't need to do anything. Just write. If you start with RTL character, the block turns into RTL. If you start with LTR character, the block turns into LTR. That's it.

If you have any particular suggest, a PR is highly appreciated.
